// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyvrribsezwtvnihobwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dnJyaWJzZXp3dHZuaWhvYndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2Njc4MzAsImV4cCI6MjA1NTI0MzgzMH0.MhpOoC_-Mtxssn60I59HKtinYw8q-KzOAY-tZ6cN_co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);